/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.mypoint.experience.controller;

import co.com.mypoint.experience.domain.Tag;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-28T20:31:26.708Z")

@Api(value = "tag", description = "the tag API")
public interface TagApi {

    @ApiOperation(value = "Nuevo tag", nickname = "addTag", notes = "Agregar nueva etiqueta", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify experience in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your experience")
            })
    }, tags={ "tag", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/tag",
        produces = { "application/xml; charset=utf-8", "application/json; charset=utf-8" }, 
        consumes = { "application/json; charset=utf-8", "application/xml; charset=utf-8" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTag(@ApiParam(value = "Objecto tag que será agregado", required = true) @Valid @RequestBody Tag body);


    @ApiOperation(value = "Lista los tag", nickname = "listTag", notes = "Lista las etiquetas", response = Tag.class, responseContainer = "List", tags={ "tag", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Tag.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid status value"),
        @ApiResponse(code = 401, message = "Unauthorized user") })
    @RequestMapping(value = "/tag",
        produces = { "application/json; charset=utf-8", "application/xml; charset=utf-8" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Tag>> listTag(@ApiParam(value = "Nombre") @Valid @RequestParam(value = "name", required = false) String name);


    @ApiOperation(value = "Actualiza tag", nickname = "updateTag", notes = "Actualiza una etiqueta", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify experience in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your experience")
            })
    }, tags={ "tag", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Experiencia not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/tag",
        produces = { "application/xml; charset=utf-8", "application/json; charset=utf-8" }, 
        consumes = { "application/json; charset=utf-8", "application/xml; charset=utf-8" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTag(@ApiParam(value = "Objecto tag que será actualizado", required = true) @Valid @RequestBody Tag body);

}
